# Tau `category2=1` Events

Load the Tau category CSV and list the events that ended up in `second_category/category1`.

In [1]:
from pathlib import Path

import pandas as pd

CSV_PATH = Path(
    "/project/def-nahee/kbas/Graphnet-Applications/Metadata/CategoryInformation/"
    "String340MC/Full_Geometry_Tau_category2_events.csv"
)

df = pd.read_csv(CSV_PATH)

category1_events = (
    df.loc[df["category_value"].astype(str) == "1", ["RunID", "EventID"]]
    .sort_values(["RunID", "EventID"])
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", None)
print(f"n_events = {len(category1_events)}")
display(category1_events)

n_events = 52

    RunID  EventID
0       4       13
1       4       15
2       4       34
3       4       50
4       4       52
5       4       54
6       4       61
7       4       65
8       4       70
9       4       73
10      4       74
11      4       76
12      4       87
13      4       91
14      4       94
15      4       96
16      4      110
17      4      134
18      4      147
19      4      151
20      4      155
21      4      158
22      4      161
23      4      166
24      4      168
25      4      177
26      4      182
27      4      183
28      5        3
29      5        8
30      5       10
31      5       43
32      5       53
33      5       62
34      5       65
35      5       69
36      5       80
37      5       84
38      5       95
39      5      103
40      5      105
41      5      107
42      5      108
43      5      126
44      5      133
45      5      134
46      5      146
47      5      157
48      5      166
49      5      177
50      5      181
51      5      200

In [2]:
unique_run_ids = sorted(category1_events["RunID"].unique().tolist())

print(f"n_unique_RunID = {len(unique_run_ids)}")
print(unique_run_ids)

n_unique_RunID = 2
[4, 5]

In [3]:
run_ids = [4,5]

tau_raw_base = Path(
    "/project/6008051/pone_simulation/"
    "MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator"
)

tau_file_paths = [tau_raw_base / f"gen_{run_id:03d}.i3.zst" for run_id in run_ids]

for path in tau_file_paths:
    print(path)

/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_004.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_005.i3.zst

In [4]:
from icecube import dataio, LeptonInjector

event_properties_fields = [
    "totalEnergy",
    "zenith",
    "azimuth",
    "finalStateX",
    "finalStateY",
    "finalType1",
    "finalType2",
    "initialType",
    "x",
    "y",
    "z",
    "totalColumnDepth",
    "radius",
    "impactParameter",
]

rows = []

for tau_file_path in tau_file_paths:
    print(f"reading {tau_file_path}")
    i3_file = dataio.I3File(str(tau_file_path))
    n_daq = 0

    while i3_file.more():
        try:
            frame = i3_file.pop_daq()
        except Exception as exc:
            if "no frame to pop" in str(exc):
                break
            raise

        n_daq += 1

        if "I3EventHeader" not in frame or "EventProperties" not in frame:
            continue

        header = frame["I3EventHeader"]
        ep = frame["EventProperties"]

        row = {
            "raw_file": tau_file_path,
            "daq_index": n_daq,
            "RunID": header.run_id,
            "SubrunID": header.sub_run_id,
            "EventID": header.event_id,
            "SubEventID": header.sub_event_id,
        }
        for field in event_properties_fields:
            row[field] = getattr(ep, field)

        rows.append(row)

raw_event_properties_df = (
    pd.DataFrame(rows)
    .sort_values(["RunID", "EventID", "SubEventID"])
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", None)
print(f"n_rows = {len(raw_event_properties_df)}")
display(raw_event_properties_df)

reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_004.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_005.i3.zst
n_rows = 400

,raw_file,daq_index,RunID,SubrunID,EventID,SubEventID,totalEnergy,zenith,azimuth,finalStateX,finalStateY,finalType1,finalType2,initialType,x,y,z,totalColumnDepth,radius,impactParameter
0,/project/6008051/pone_simulation/MC000004-nu_t...,1,4,4294967295,1,0,278404.465310,0.762805,1.795441,0.003889,0.335883,-12,-2000001006,-12,-582.135794,953.639166,1611.977544,3.772313e+05,1117.277826,497.168506
1,/project/6008051/pone_simulation/MC000004-nu_t...,2,4,4294967295,2,0,479.659520,1.745862,4.613300,0.143346,0.433998,-12,-2000001006,-12,-965.476213,-229.748926,-286.015491,4.343534e+05,992.435836,964.663916
2,/project/6008051/pone_simulation/MC000004-nu_t...,3,4,4294967295,3,0,231.925835,1.547583,3.101871,0.069249,0.554309,-12,-2000001006,-12,-2073.264946,-269.790218,-319.368051,3.353363e+05,2090.744915,508.542870
3,/project/6008051/pone_simulation/MC000004-nu_t...,4,4,4294967295,4,0,261.478809,2.144377,0.815938,0.325833,0.808219,-12,-2000001006,-12,233.049061,934.708189,381.993973,3.482837e+05,963.323031,908.411356
4,/project/6008051/pone_simulation/MC000004-nu_t...,5,4,4294967295,5,0,6118.632066,2.432875,1.925977,0.104540,0.342195,-12,-2000001006,-12,-92.615147,2598.574414,-1768.405608,1.227872e+06,2600.224327,1090.961638
5,/project/6008051/pone_simulation/MC000004-nu_t...,6,4,4294967295,6,0,2030.443942,1.964984,4.533721,0.201131,0.278803,-12,-2000001006,-12,85.543326,-3597.219941,-790.770521,8.049697e+05,3598.236924,955.132589
6,/project/6008051/pone_simulation/MC000004-nu_t...,7,4,4294967295,7,0,847.449454,2.670903,4.962259,0.139760,0.991729,-12,-2000001006,-12,-402.641290,-944.789840,-1599.081287,6.298772e+05,1027.009177,623.765666
7,/project/6008051/pone_simulation/MC000004-nu_t...,8,4,4294967295,8,0,157.005300,1.460940,4.936198,0.078207,0.195359,-12,-2000001006,-12,374.312149,1006.606314,63.963444,3.008502e+05,1073.948722,610.302760
8,/project/6008051/pone_simulation/MC000004-nu_t...,9,4,4294967295,9,0,523.460721,1.546919,4.056005,0.545401,0.227779,-12,-2000001006,-12,-800.016103,375.693043,685.321215,4.499105e+05,883.838801,1099.104222
9,/project/6008051/pone_simulation/MC000004-nu_t...,10,4,4294967295,10,0,2178.693019,1.331050,0.480010,0.117304,0.218911,-12,-2000001006,-12,3821.370480,2211.549368,189.130877,1.192667e+06,4415.180965,885.822207
10,/project/6008051/pone_simulation/MC000004-nu_t...,11,4,4294967295,11,0,572.942957,2.702248,2.000801,0.160074,0.200130,-12,-2000001006,-12,-702.672691,-799.811619,446.428602,5.627492e+05,1064.634931,993.087022
11,/project/6008051/pone_simulation/MC000004-nu_t...,12,4,4294967295,12,0,175.799911,2.127164,5.369636,0.014615,0.449527,-12,-2000001006,-12,-752.050914,-196.821095,776.824483,3.097379e+05,777.379650,872.600977
12,/project/6008051/pone_simulation/MC000004-nu_t...,13,4,4294967295,13,0,138.922729,2.193671,5.536081,0.212596,0.842929,-12,-2000001006,-12,678.268873,165.214892,-251.775310,3.114482e+05,698.100727,582.461201
13,/project/6008051/pone_simulation/MC000004-nu_t...,14,4,4294967295,14,0,2044.548688,1.139280,0.310798,0.088232,0.086722,-12,-2000001006,-12,5736.313770,1988.316999,1602.304535,1.157784e+06,6071.136645,1092.012643
14,/project/6008051/pone_simulation/MC000004-nu_t...,15,4,4294967295,15,0,666.056531,2.027775,3.409304,0.572683,0.157191,-12,-2000001006,-12,297.707734,19.452979,164.641437,4.973122e+05,298.342610,62.866719
15,/project/6008051/pone_simulation/MC000004-nu_t...,16,4,4294967295,16,0,340.061056,0.589878,5.497320,0.138090,0.055926,-12,-2000001006,-12,-229.264308,1160.340375,-73.226713,3.195312e+05,1182.772975,1017.414605
16,/project/6008051/pone_simulation/MC000004-nu_t...,17,4,4294967295,17,0,251.078693,0.618461,4.551672,0.088892,0.254840,-12,-2000001006,-12,268.993787,-192.364785,1749.406417,3.130677e+05,330.699059,942.426872
17,/project/6008051/pone_simulation/MC000004-nu_t...,18,4,4294967295,18,0,124.523019,0.645413,4.097839,0.119894,0.196046,-12,-2000001006,-12,187.317285,22.851762,-1025.838454,4.158715e+05,188.706037,534.500550
18,/project/6008051/pone_simulation/MC000004-nu_t...,19,4,4294967295,19,0,893.876226,1.213000,1.985891,0.112965,0.145390,-12,-2000001006,-12,-1871.738599,1841.156485,707.572761,5.680397e+05,2625.502349,989.033129
19,/project/6008051/pone_simulation/MC000004-nu_t...,20,4,4294967295,20,0,180.486092,2.268014,0.591629,0.192075,0.559172,-12,-2000001006,-12,1022.668065,1310.096243,-624.361162,3.119285e+05,1661.987405,744.410627
20,/project/6008051/pone_simulation/MC000004-nu_t...,21,4,4294967295,21,0,188.235553,0.769520,5.572401,0.038323,0.383410,-12,-2000001006,-12,616.866228,-405.854900,1783.759577,3.155291e+05,738.405135,721.430402
21,/project/6008051/pone_simulation/MC000004-nu_t...,22,4,4294967295,22,0,111308.990793,0.628889,4.664240,0.072301,0.094720,-12,-2000001006,-12,-598.813850,-66.280233,-1127.108860,5.890718e+05,602.470826,949.388478
22,/project/6008051/pone_simulation/MC000004-nu_t...,23,4,4294967295,23,0,2511.215523,1.580942,0.184169,0.147264,0.130417,-12,-2000001006,-12,7235.746476,2362.010113,328.034630,8.788944e+05,7611.512257,1075.947018
23,/project/6008051/pone_simulation/MC000004-nu_t...,24,4,4294967295,24,0,207.597801,1.650976,2.965902,0.132963,0.600783,-12,-2000001006,-12,-823.086537,-149.742382,950.465170,3.244085e+05,836.596814,1051.385486
24,/project/6008051/pone_simulation/MC000004-nu_t...,25,4,4294967295,25,0,279.184430,2.454957,1.747232,0.162322,0.437600,-12,-2000001006,-12,-149.630885,1075.058315,-910.086882,3.831600e+05,1085.421477,265.146983
25,/project/6008051/pone_simulation/MC000004-nu_t...,26,4,4294967295,26,0,2135.497590,2.620372,4.271997,0.252362,0.451642,-12,-2000001006,-12,-994.034686,-1501.879113,-1704.339281,8.316148e+05,1801.040207,743.547114
26,/project/6008051/pone_simulation/MC000004-nu_t...,27,4,4294967295,27,0,1285.783051,0.619056,0.323198,0.251692,0.006244,-12,-2000001006,-12,-692.746963,761.981470,-405.646469,4.260341e+05,1029.812660,948.103392
27,/project/6008051/pone_simulation/MC000004-nu_t...,28,4,4294967295,28,0,584.905568,1.777749,2.425610,0.131035,0.576037,-12,-2000001006,-12,795.003332,-429.554791,804.262319,4.709147e+05,903.630243,637.370549
28,/project/6008051/pone_simulation/MC000004-nu_t...,29,4,4294967295,29,0,164.328725,1.438573,0.821158,0.222022,0.230049,-12,-2000001006,-12,352.615094,1118.458158,-739.762288,6.679930e+05,1172.725909,1007.960048
29,/project/6008051/pone_simulation/MC000004-nu_t...,30,4,4294967295,30,0,163092.385171,2.503666,2.051699,0.014361,0.414439,-12,-2000001006,-12,-2201.653921,3932.608402,-6938.905077,2.868193e+06,4506.960043,530.217518
30,/project/6008051/pone_simulation/MC000004-nu_t...,31,4,4294967295,31,0,4062.317334,1.159682,3.733906,0.117802,0.204798,-12,-2000001006,-12,-3624.492055,-1421.651941,1775.316899,6.278261e+05,3893.332365,850.956610
31,/project/6008051/pone_simulation/MC000004-nu_t...,32,4,4294967295,32,0,1155.193472,3.043905,3.367302,0.113110,0.385555,-12,-2000001006,-12,-240.831418,-595.323660,-832.182710,7.161099e+05,642.191586,598.552182
32,/project/6008051/pone_simulation/MC000004-nu_t...,33,4,4294967295,33,0,2256.988586,1.647571,5.381367,0.220462,0.273750,-12,-2000001006,-12,3177.807098,-3844.592320,-343.583093,8.412307e+05,4987.920214,115.597415
33,/project/6008051/pone_simulation/MC000004-nu_t...,34,4,4294967295,34,0,146.763673,2.608412,1.558423,0.089981,0.125878,-12,-2000001006,-12,464.340614,290.421808,-483.545677,3.699474e+05,547.683332,460.804759
34,/project/6008051/pone_simulation/MC000004-nu_t...,35,4,4294967295,35,0,117.946556,0.447347,1.967579,0.260305,0.185166,-12,-2000001006,-12,-175.377065,916.450182,1227.215989,3.847239e+05,933.079873,349.960749
35,/project/6008051/pone_simulation/MC000004-nu_t...,36,4,4294967295,36,0,975.220205,0.396958,0.557947,0.263321,0.112006,-12,-2000001006,-12,851.396456,705.810398,1656.885914,4.685675e+05,1105.913308,398.658404
36,/project/6008051/pone_simulation/MC000004-nu_t...,37,4,4294967295,37,0,274.459858,0.481746,4.134201,0.108891,0.188544,-12,-2000001006,-12,-599.792532,488.441763,-734.449016,4.549706e+05,773.515635,814.677080
37,/project/6008051/pone_simulation/MC000004-nu_t...,38,4,4294967295,38,0,142.189476,0.937762,4.284611,0.091848,0.047659,-12,-2000001006,-12,663.235727,262.834574,-1139.254352,4.582888e+05,713.416879,788.527114
38,/project/6008051/pone_simulation/MC000004-nu_t...,39,4,4294967295,39,0,109.241855,1.354657,4.191348,0.114650,0.184992,-12,-2000001006,-12,-553.787846,1165.594575,-137.888238,2.774907e+05,1290.461814,1060.763934
39,/project/6008051/pone_simulation/MC000004-nu_t...,40,4,4294967295,40,0,233.741859,0.651758,6.205735,0.207206,0.121796,-12,-2000001006,-12,256.385010,-978.225466,1217.077321,3.422367e+05,1011.265709,1066.955607
40,/project/6008051/pone_simulation/MC000004-nu_t...,41,4,4294967295,41,0,485.867599,1.715404,1.095579,0.089744,0.109726,-12,-2000001006,-12,523.042102,1452.477101,-573.070012,4.365894e+05,1543.781969,399.801693
41,/project/6008051/pone_simulation/MC000004-nu_t...,42,4,4294967295,42,0,250.736032,1.442506,3.039005,0.197484,0.250371,-12,-2000001006,-12,808.452237,-752.790122,-295.501038,3.436177e+05,1104.666459,690.018994
42,/project/6008051/pone_simulation/MC000004-nu_t...,43,4,4294967295,43,0,894.522605,2.147046,3.122101,0.190915,0.638055,-12,-2000001006,-12,1242.877598,-583.436119,-135.575732,7.802150e+05,1373.004890,973.528939
43,/project/6008051/pone_simulation/MC000004-nu_t...,44,4,4294967295,44,0,1925.503561,2.533697,4.089197,0.037025,0.056007,-12,-2000001006,-12,-1153.157713,-1862.212759,-1557.408316,7.871930e+05,2190.344509,916.634133
44,/project/6008051/pone_simulation/MC000004-nu_t...,45,4,4294967295,45,0,82393.403971,1.251535,5.432691,0.053071,0.281518,-12,-2000001006,-12,2969.280309,-4519.397248,1727.187681,8.121749e+05,5407.548154,750.432892
45,/project/6008051/pone_simulation/MC000004-nu_t...,46,4,4294967295,46,0,131.578980,1.826218,0.668382,0.421500,0.082575,-12,-2000001006,-12,-890.301839,-108.956086,271.723742,2.885572e+05,896.944141,471.347568
46,/project/6008051/pone_simulation/MC000004-nu_t...,47,4,4294967295,47,0,139.542100,1.632779,0.515177,0.182283,0.062948,-12,-2000001006,-12,1895.533887,49.305184,-319.051307,2.924413e+05,1896.175023,916.519236
47,/project/6008051/pone_simulation/MC000004-nu_t...,48,4,4294967295,48,0,349.871516,1.198792,1.802294,0.280338,0.551968,-12,-2000001006,-12,222.050097,961.695887,1400.403594,3.850397e+05,986.998087,1075.575147
48,/project/6008051/pone_simulation/MC000004-nu_t...,49,4,4294967295,49,0,219.372131,2.329809,5.265163,0.036625,0.141683,-12,-2000001006,-12,198.717840,-304.352936,766.607940,3.297286e+05,363.482447,806.308354
49,/project/6008051/pone_simulation/MC000004-nu_t...,50,4,4294967295,50,0,150.173527,1.539285,4.576754,0.045381,0.943448,-12,-2000001006,-12,404.710343,-330.561449,-68.000475,2.975781e+05,522.552708,452.219675
50,/project/6008051/pone_simulation/MC000004-nu_t...,51,4,4294967295,51,0,4095.503463,1.710845,5.661052,0.197821,0.249772,-12,-2000001006,-12,5743.324138,-4687.668103,-682.626215,1.063766e+06,7413.501494,584.070961
51,/project/6008051/pone_simulation/MC000004-nu_t...,52,4,4294967295,52,0,583.332548,1.274988,5.648554,0.204607,0.156552,-12,-2000001006,-12,297.871663,520.497942,188.523646,4.703883e+05,599.704623,628.546446
52,/project/6008051/pone_simulation/MC000004-nu_t...,53,4,4294967295,53,0,320.474677,2.150564,1.061180,0.140038,0.415980,-12,-2000001006,-12,1066.123875,562.633801,-1476.502400,5.588422e+05,1205.477877,945.861654
53,/project/6008051/pone_simulation/MC000004-nu_t...,54,4,4294967295,54,0,143.989897,0.878142,1.087215,0.121590,0.238983,-12,-2000001006,-12,-448.105610,363.778918,185.672024,3.182273e+05,577.177390,570.209723
54,/project/6008051/pone_simulation/MC000004-nu_t...,55,4,4294967295,55,0,4761.933583,0.264021,5.516937,0.221459,0.591524,-12,-2000001006,-12,105.845468,-1272.321682,1877.594776,4.525576e+05,1276.716776,949.067836
55,/project/6008051/pone_simulation/MC000004-nu_t...,56,4,4294967295,56,0,369.485915,1.381225,5.593129,0.152986,0.697935,-12,-2000001006,-12,1478.079726,-506.832193,-197.033531,4.901462e+05,1562.561534,722.914007
56,/project/6008051/pone_simulation/MC000004-nu_t...,57,4,4294967295,57,0,4730.501573,1.269262,4.149346,0.118412,0.023417,-12,-2000001006,-12,-2230.998155,-3159.699709,1177.211357,8.461444e+05,3867.952303,201.410841
57,/project/6008051/pone_simulation/MC000004-nu_t...,58,4,4294967295,58,0,1352.036222,2.228011,2.095244,0.290104,0.147819,-12,-2000001006,-12,531.741534,1114.931982,-488.362939,6.987524e+05,1235.241832,1019.357772
58,/project/6008051/pone_simulation/MC000004-nu_t...,59,4,4294967295,59,0,109.141843,1.842839,4.229579,0.202462,0.148985,-12,-2000001006,-12,329.667358,-645.680446,286.923977,2.774405e+05,724.971590,708.112705
59,/project/6008051/pone_simulation/MC000004-nu_t...,60,4,4294967295,60,0,97774.569610,0.632260,5.146641,0.025825,0.253748,-12,-2000001006,-12,704.861044,-1214.131249,616.280675,5.950714e+05,1403.903053,774.310821
60,/project/6008051/pone_simulation/MC000004-nu_t...,61,4,4294967295,61,0,1376.987717,2.396932,3.271515,0.097613,0.093863,-12,-2000001006,-12,157.359411,430.747228,-296.092099,7.926167e+05,458.590404,540.811382
61,/project/6008051/pone_simulation/MC000004-nu_t...,62,4,4294967295,62,0,8704.783294,1.091205,5.135309,0.027670,0.098385,-12,-2000001006,-12,637.002201,-1563.817565,1754.476748,4.312764e+05,1688.578450,780.296943
62,/project/6008051/pone_simulation/MC000004-nu_t...,63,4,4294967295,63,0,453.495539,2.225919,2.547844,0.061425,0.451770,-12,-2000001006,-12,-22.835156,-0.857000,-499.903201,5.383902e+05,22.851231,385.406789
63,/project/6008051/pone_simulation/MC000004-nu_t...,64,4,4294967295,64,0,418.235051,1.221179,2.413695,0.039685,0.484300,-12,-2000001006,-12,-2571.796205,1006.806949,542.739788,4.956652e+05,2761.846475,1030.862043
64,/project/6008051/pone_simulation/MC000004-nu_t...,65,4,4294967295,65,0,420.135645,1.730057,2.092255,0.160165,0.136204,-12,-2000001006,-12,233.403202,67.786186,-374.280097,4.123664e+05,243.047365,446.263255
65,/project/6008051/pone_simulation/MC000004-nu_t...,66,4,4294967295,66,0,186.068275,1.821839,0.489450,0.357428,0.394465,-12,-2000001006,-12,924.229911,853.966487,-862.600688,4.693869e+05,1258.355947,621.427607
66,/project/6008051/pone_simulation/MC000004-nu_t...,67,4,4294967295,67,0,9616.782222,1.283885,3.760251,0.074613,0.249110,-12,-2000001006,-12,-2129.715728,-496.485623,1308.816457,6.445484e+05,2186.821222,1075.293713
67,/project/6008051/pone_simulation/MC000004-nu_t...,68,4,4294967295,68,0,2094.357811,1.274570,2.896254,0.378381,0.003013,-12,-2000001006,-12,-5694.376976,1925.766226,1832.478732,8.154814e+05,6011.198275,485.036594
68,/project/6008051/pone_simulation/MC000004-nu_t...,69,4,4294967295,69,0,666.768225,0.824629,0.797591,0.210279,0.994757,-12,-2000001006,-12,-391.630270,644.089273,-594.190320,6.375304e+05,753.807177,922.322333
69,/project/6008051/pone_simulation/MC000004-nu_t...,70,4,4294967295,70,0,44840.585740,0.270948,5.012687,0.097993,0.308836,-12,-2000001006,-12,135.999474,-131.347974,-462.098770,4.424923e+05,189.071804,297.605966
70,/project/6008051/pone_simulation/MC000004-nu_t...,71,4,4294967295,71,0,125.666393,2.621387,1.661834,0.238531,0.132453,-12,-2000001006,-12,15.958340,59.328396,876.850253,3.153590e+05,61.437181,486.320432
71,/project/6008051/pone_simulation/MC000004-nu_t...,72,4,4294967295,72,0,315714.675182,1.995324,4.416355,0.040278,0.099206,-12,-2000001006,-12,-1279.219531,-5636.427959,-2244.584646,3.052668e+06,5779.768399,534.080598
72,/project/6008051/pone_simulation/MC000004-nu_t...,73,4,4294967295,73,0,535.258858,0.723925,4.551982,0.038119,0.897498,-12,-2000001006,-12,-626.110054,-161.422637,-277.175711,5.472674e+05,646.584153,702.573560
73,/project/6008051/pone_simulation/MC000004-nu_t...,74,4,4294967295,74,0,179.715315,1.123370,3.536900,0.068897,0.232368,-12,-2000001006,-12,-360.028610,381.570376,90.118630,3.115689e+05,524.610857,490.788194
74,/project/6008051/pone_simulation/MC000004-nu_t...,75,4,4294967295,75,0,202.450375,0.700280,0.857136,0.125246,0.635420,-12,-2000001006,-12,-123.154912,-134.231387,-1085.629111,4.615476e+05,182.168048,560.398587
75,/project/6008051/pone_simulation/MC000004-nu_t...,76,4,4294967295,76,0,414.947177,1.975715,3.818233,0.412318,0.812978,-12,-2000001006,-12,743.177256,-77.707872,-382.913975,5.748844e+05,747.228845,769.022808
76,/project/6008051/pone_simulation/MC000004-nu_t...,77,4,4294967295,77,0,1132.486553,1.740744,0.537303,0.468409,0.298113,-12,-2000001006,-12,1768.341052,691.897464,-971.453262,8.804688e+05,1898.881822,711.981988
77,/project/6008051/pone_simulation/MC000004-nu_t...,78,4,4294967295,78,0,1697.950786,1.304842,2.284568,0.184351,0.126916,-12,-2000001006,-12,-3956.982648,3542.138246,907.072563,8.868363e+05,5310.786667,843.328994
78,/project/6008051/pone_simulation/MC000004-nu_t...,79,4,4294967295,79,0,1621.630512,1.171766,2.262194,0.021394,0.139046,-12,-2000001006,-12,-2972.640805,3382.954721,718.278980,1.095303e+06,4503.440462,1095.188927
79,/project/6008051/pone_simulation/MC000004-nu_t...,80,4,4294967295,80,0,111.668870,1.106970,1.045032,0.097814,0.494269,-12,-2000001006,-12,1174.783793,366.670891,1140.656013,2.787056e+05,1230.676441,1034.399679
80,/project/6008051/pone_simulation/MC000004-nu_t...,81,4,4294967295,81,0,1840.669009,2.727760,6.072374,0.082561,0.155776,-12,-2000001006,-12,219.666854,783.917415,-752.396023,8.721749e+05,814.113039,851.925064
81,/project/6008051/pone_simulation/MC000004-nu_t...,82,4,4294967295,82,0,139.769642,2.760992,0.570064,0.410054,0.138423,-12,-2000001006,-12,951.278566,-602.021273,-997.705024,3.704860e+05,1125.771079,1022.698890
82,/project/6008051/pone_simulation/MC000004-nu_t...,83,4,4294967295,83,0,393.664198,2.394953,2.826045,0.312562,0.198034,-12,-2000001006,-12,-1777.515238,112.465713,-611.974862,4.022538e+05,1781.069611,959.499616
83,/project/6008051/pone_simulation/MC000004-nu_t...,84,4,4294967295,84,0,123.106834,1.791273,1.840398,0.131723,0.363119,-12,-2000001006,-12,-141.971724,962.676192,268.070275,2.843899e+05,973.088598,487.662512
84,/project/6008051/pone_simulation/MC000004-nu_t...,85,4,4294967295,85,0,158.125424,2.791488,1.598206,0.401202,0.144741,-12,-2000001006,-12,125.115472,779.788319,-1102.007043,3.640069e+05,789.761802,380.326211
85,/project/6008051/pone_simulation/MC000004-nu_t...,86,4,4294967295,86,0,27502.524629,1.477372,1.295051,0.049779,0.008031,-12,-2000001006,-12,2100.515785,5379.496968,768.053336,1.899050e+06,5775.045818,601.586397
86,/project/6008051/pone_simulation/MC000004-nu_t...,87,4,4294967295,87,0,133.589031,2.585480,6.004209,0.018739,0.824703,-12,-2000001006,-12,-193.634975,-394.932583,343.657641,3.510730e+05,439.847984,448.171953
87,/project/6008051/pone_simulation/MC000004-nu_t...,88,4,4294967295,88,0,182.325425,2.775534,1.573725,0.199658,0.045545,-12,-2000001006,-12,-788.958731,112.723629,273.830962,3.829838e+05,796.970825,814.941688
88,/project/6008051/pone_simulation/MC000004-nu_t...,89,4,4294967295,89,0,1234.876451,1.702978,5.389792,0.293932,0.130080,-12,-2000001006,-12,2340.651959,-1317.431354,-216.660213,6.500937e+05,2685.940612,1004.590807
89,/project/6008051/pone_simulation/MC000004-nu_t...,90,4,4294967295,90,0,2740.359782,2.224823,2.788426,0.100251,0.464721,-12,-2000001006,-12,-424.293534,622.504080,-753.017316,9.893551e+05,753.350073,491.559730
90,/project/6008051/pone_simulation/MC000004-nu_t...,91,4,4294967295,91,0,4528.189650,1.989220,0.853144,0.355388,0.252990,-12,-2000001006,-12,802.681492,86.264549,423.410345,1.103906e+06,807.303630,833.286717
91,/project/6008051/pone_simulation/MC000004-nu_t...,92,4,4294967295,92,0,3350.224271,2.434827,2.312025,0.008590,0.639046,-12,-2000001006,-12,-1273.305401,1280.734735,-3076.407979,1.134634e+06,1805.986740,629.947922
92,/project/6008051/pone_simulation/MC000004-nu_t...,93,4,4294967295,93,0,421.651014,0.963213,4.525090,0.034278,0.461918,-12,-2000001006,-12,-695.455291,-755.754962,626.020594,4.296260e+05,1027.046067,542.806291

In [5]:
print(f"total DAQ/EventProperties rows = {len(raw_event_properties_df)}")
print(f"unique RunID count = {raw_event_properties_df['RunID'].nunique()}")
print(f"unique EventID count = {raw_event_properties_df[['RunID', 'EventID', 'SubEventID']].drop_duplicates().shape[0]}")

for column in ["finalType1", "finalType2", "initialType"]:
    values = raw_event_properties_df[column].drop_duplicates().tolist()
    print(f"\nunique {column} ({len(values)}):")
    print(values)

total DAQ/EventProperties rows = 400
unique RunID count = 2
unique EventID count = 400

unique finalType1 (2):
[-12, 12]

unique finalType2 (1):
[-2000001006]

unique initialType (2):
[-12, 12]

to move:

mv /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_002.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_008.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_009.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_011.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_012.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_208.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_224.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_326.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_335.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_707.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_929.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Electron_PMT_Response/

to move

mv /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_002.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_008.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_009.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_011.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_012.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_208.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_224.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_326.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_335.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_707.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_929.i3.gz /home/kbas/scratch/String340MC/102_string/Electron_PMT_Response/