# Tau `category2=1` Events

Load the Tau category CSV and list the events that ended up in `second_category/category1`.

In [1]:
from pathlib import Path

import pandas as pd

CSV_PATH = Path(
    "/project/def-nahee/kbas/Graphnet-Applications/Metadata/CategoryInformation/"
    "String340MC/Full_Geometry_Tau_category2_events.csv"
)

df = pd.read_csv(CSV_PATH)

category1_events = (
    df.loc[df["category_value"].astype(str) == "1", ["RunID", "EventID"]]
    .sort_values(["RunID", "EventID"])
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", None)
print(f"n_events = {len(category1_events)}")
display(category1_events)

n_events = 52

    RunID  EventID
0       4       13
1       4       15
2       4       34
3       4       50
4       4       52
5       4       54
6       4       61
7       4       65
8       4       70
9       4       73
10      4       74
11      4       76
12      4       87
13      4       91
14      4       94
15      4       96
16      4      110
17      4      134
18      4      147
19      4      151
20      4      155
21      4      158
22      4      161
23      4      166
24      4      168
25      4      177
26      4      182
27      4      183
28      5        3
29      5        8
30      5       10
31      5       43
32      5       53
33      5       62
34      5       65
35      5       69
36      5       80
37      5       84
38      5       95
39      5      103
40      5      105
41      5      107
42      5      108
43      5      126
44      5      133
45      5      134
46      5      146
47      5      157
48      5      166
49      5      177
50      5      181
51      5      200

In [2]:
unique_run_ids = sorted(category1_events["RunID"].unique().tolist())

print(f"n_unique_RunID = {len(unique_run_ids)}")
print(unique_run_ids)

n_unique_RunID = 2
[4, 5]

In [3]:
run_ids = [2, 8, 9, 11, 12, 208, 224, 326, 335, 707, 929]

tau_raw_base = Path(
    "/project/6008051/pone_simulation/"
    "MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator"
)

tau_file_paths = [tau_raw_base / f"gen_{run_id:03d}.i3.zst" for run_id in run_ids]

for path in tau_file_paths:
    print(path)

/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_002.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_008.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_009.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_011.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_012.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_208.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_224.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_326.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_335.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_707.i3.zst
/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_929.i3.zst

In [4]:
from icecube import dataio, LeptonInjector

event_properties_fields = [
    "totalEnergy",
    "zenith",
    "azimuth",
    "finalStateX",
    "finalStateY",
    "finalType1",
    "finalType2",
    "initialType",
    "x",
    "y",
    "z",
    "totalColumnDepth",
    "radius",
    "impactParameter",
]

rows = []

for tau_file_path in tau_file_paths:
    print(f"reading {tau_file_path}")
    i3_file = dataio.I3File(str(tau_file_path))
    n_daq = 0

    while i3_file.more():
        try:
            frame = i3_file.pop_daq()
        except Exception as exc:
            if "no frame to pop" in str(exc):
                break
            raise

        n_daq += 1

        if "I3EventHeader" not in frame or "EventProperties" not in frame:
            continue

        header = frame["I3EventHeader"]
        ep = frame["EventProperties"]

        row = {
            "raw_file": tau_file_path,
            "daq_index": n_daq,
            "RunID": header.run_id,
            "SubrunID": header.sub_run_id,
            "EventID": header.event_id,
            "SubEventID": header.sub_event_id,
        }
        for field in event_properties_fields:
            row[field] = getattr(ep, field)

        rows.append(row)

raw_event_properties_df = (
    pd.DataFrame(rows)
    .sort_values(["RunID", "EventID", "SubEventID"])
    .reset_index(drop=True)
)

pd.set_option("display.max_rows", None)
print(f"n_rows = {len(raw_event_properties_df)}")
display(raw_event_properties_df)

reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_002.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_008.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_009.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_011.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_012.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_208.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_224.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_326.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_335.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_707.i3.zst
reading /project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_929.i3.zst
n_rows = 2200

                                               raw_file  daq_index  RunID  \
0     /project/6008051/pone_simulation/MC000004-nu_t...          1      2
1     /project/6008051/pone_simulation/MC000004-nu_t...          2      2
2     /project/6008051/pone_simulation/MC000004-nu_t...          3      2
3     /project/6008051/pone_simulation/MC000004-nu_t...          4      2
4     /project/6008051/pone_simulation/MC000004-nu_t...          5      2
5     /project/6008051/pone_simulation/MC000004-nu_t...          6      2
6     /project/6008051/pone_simulation/MC000004-nu_t...          7      2
7     /project/6008051/pone_simulation/MC000004-nu_t...          8      2
8     /project/6008051/pone_simulation/MC000004-nu_t...          9      2
9     /project/6008051/pone_simulation/MC000004-nu_t...         10      2
10    /project/6008051/pone_simulation/MC000004-nu_t...         11      2
11    /project/6008051/pone_simulation/MC000004-nu_t...         12      2
12    /project/6008051/pone_simulation/MC000004-nu_t...         13      2
13    /project/6008051/pone_simulation/MC000004-nu_t...         14      2
14    /project/6008051/pone_simulation/MC000004-nu_t...         15      2
15    /project/6008051/pone_simulation/MC000004-nu_t...         16      2
16    /project/6008051/pone_simulation/MC000004-nu_t...         17      2
17    /project/6008051/pone_simulation/MC000004-nu_t...         18      2
18    /project/6008051/pone_simulation/MC000004-nu_t...         19      2
19    /project/6008051/pone_simulation/MC000004-nu_t...         20      2
20    /project/6008051/pone_simulation/MC000004-nu_t...         21      2
21    /project/6008051/pone_simulation/MC000004-nu_t...         22      2
22    /project/6008051/pone_simulation/MC000004-nu_t...         23      2
23    /project/6008051/pone_simulation/MC000004-nu_t...         24      2
24    /project/6008051/pone_simulation/MC000004-nu_t...         25      2
25    /project/6008051/pone_simulation/MC000004-nu_t...         26      2
26    /project/6008051/pone_simulation/MC000004-nu_t...         27      2
27    /project/6008051/pone_simulation/MC000004-nu_t...         28      2
28    /project/6008051/pone_simulation/MC000004-nu_t...         29      2
29    /project/6008051/pone_simulation/MC000004-nu_t...         30      2
30    /project/6008051/pone_simulation/MC000004-nu_t...         31      2
31    /project/6008051/pone_simulation/MC000004-nu_t...         32      2
32    /project/6008051/pone_simulation/MC000004-nu_t...         33      2
33    /project/6008051/pone_simulation/MC000004-nu_t...         34      2
34    /project/6008051/pone_simulation/MC000004-nu_t...         35      2
35    /project/6008051/pone_simulation/MC000004-nu_t...         36      2
36    /project/6008051/pone_simulation/MC000004-nu_t...         37      2
37    /project/6008051/pone_simulation/MC000004-nu_t...         38      2
38    /project/6008051/pone_simulation/MC000004-nu_t...         39      2
39    /project/6008051/pone_simulation/MC000004-nu_t...         40      2
40    /project/6008051/pone_simulation/MC000004-nu_t...         41      2
41    /project/6008051/pone_simulation/MC000004-nu_t...         42      2
42    /project/6008051/pone_simulation/MC000004-nu_t...         43      2
43    /project/6008051/pone_simulation/MC000004-nu_t...         44      2
44    /project/6008051/pone_simulation/MC000004-nu_t...         45      2
45    /project/6008051/pone_simulation/MC000004-nu_t...         46      2
46    /project/6008051/pone_simulation/MC000004-nu_t...         47      2
47    /project/6008051/pone_simulation/MC000004-nu_t...         48      2
48    /project/6008051/pone_simulation/MC000004-nu_t...         49      2
49    /project/6008051/pone_simulation/MC000004-nu_t...         50      2
50    /project/6008051/pone_simulation/MC000004-nu_t...         51      2
51    /project/6008051/pone_simulation/MC000004-nu_t...         52      2
52    /project/6008051/pone_simulation/MC000004-nu_t...         53      2
53    /project/6008051/pone_simulation/MC000004-nu_t...         54      2
54    /project/6008051/pone_simulation/MC000004-nu_t...         55      2
55    /project/6008051/pone_simulation/MC000004-nu_t...         56      2
56    /project/6008051/pone_simulation/MC000004-nu_t...         57      2
57    /project/6008051/pone_simulation/MC000004-nu_t...         58      2
58    /project/6008051/pone_simulation/MC000004-nu_t...         59      2
59    /project/6008051/pone_simulation/MC000004-nu_t...         60      2
60    /project/6008051/pone_simulation/MC000004-nu_t...         61      2
61    /project/6008051/pone_simulation/MC000004-nu_t...         62      2
62    /project/6008051/pone_simulation/MC000004-nu_t...         63      2
63    /project/6008051/pone_simulation/MC000004-nu_t...         64      2
64    /project/6008051/pone_simulation/MC000004-nu_t...         65      2
65    /project/6008051/pone_simulation/MC000004-nu_t...         66      2
66    /project/6008051/pone_simulation/MC000004-nu_t...         67      2
67    /project/6008051/pone_simulation/MC000004-nu_t...         68      2
68    /project/6008051/pone_simulation/MC000004-nu_t...         69      2
69    /project/6008051/pone_simulation/MC000004-nu_t...         70      2
70    /project/6008051/pone_simulation/MC000004-nu_t...         71      2
71    /project/6008051/pone_simulation/MC000004-nu_t...         72      2
72    /project/6008051/pone_simulation/MC000004-nu_t...         73      2
73    /project/6008051/pone_simulation/MC000004-nu_t...         74      2
74    /project/6008051/pone_simulation/MC000004-nu_t...         75      2
75    /project/6008051/pone_simulation/MC000004-nu_t...         76      2
76    /project/6008051/pone_simulation/MC000004-nu_t...         77      2
77    /project/6008051/pone_simulation/MC000004-nu_t...         78      2
78    /project/6008051/pone_simulation/MC000004-nu_t...         79      2
79    /project/6008051/pone_simulation/MC000004-nu_t...         80      2
80    /project/6008051/pone_simulation/MC000004-nu_t...         81      2
81    /project/6008051/pone_simulation/MC000004-nu_t...         82      2
82    /project/6008051/pone_simulation/MC000004-nu_t...         83      2
83    /project/6008051/pone_simulation/MC000004-nu_t...         84      2
84    /project/6008051/pone_simulation/MC000004-nu_t...         85      2
85    /project/6008051/pone_simulation/MC000004-nu_t...         86      2
86    /project/6008051/pone_simulation/MC000004-nu_t...         87      2
87    /project/6008051/pone_simulation/MC000004-nu_t...         88      2
88    /project/6008051/pone_simulation/MC000004-nu_t...         89      2
89    /project/6008051/pone_simulation/MC000004-nu_t...         90      2
90    /project/6008051/pone_simulation/MC000004-nu_t...         91      2
91    /project/6008051/pone_simulation/MC000004-nu_t...         92      2
92    /project/6008051/pone_simulation/MC000004-nu_t...         93      2
93    /project/6008051/pone_simulation/MC000004-nu_t...         94      2
94    /project/6008051/pone_simulation/MC000004-nu_t...         95      2
95    /project/6008051/pone_simulation/MC000004-nu_t...         96      2
96    /project/6008051/pone_simulation/MC000004-nu_t...         97      2
97    /project/6008051/pone_simulation/MC000004-nu_t...         98      2
98    /project/6008051/pone_simulation/MC000004-nu_t...         99      2
99    /project/6008051/pone_simulation/MC000004-nu_t...        100      2
100   /project/6008051/pone_simulation/MC000004-nu_t...        101      2
101   /project/6008051/pone_simulation/MC000004-nu_t...        102      2
102   /project/6008051/pone_simulation/MC000004-nu_t...        103      2
103   /project/6008051/pone_simulation/MC000004-nu_t...        104      2
104   /project/6008051/pone_simulation/MC000004-nu_t...        105      2
105   /project/6008051/pone_simulation/MC000004-nu_t...        106      2
106   /project/6008051/pone_simulation/MC000004-nu_t...        107      2
107   /project/6008051/pone_simulation/MC000004-nu_t...        108      2
108   /project/6008051/pone_simulation/MC000004-nu_t...        109      2
109   /project/6008051/pone_simulation/MC000004-nu_t...        110      2
110   /project/6008051/pone_simulation/MC000004-nu_t...        111      2
111   /project/6008051/pone_simulation/MC000004-nu_t...        112      2
112   /project/6008051/pone_simulation/MC000004-nu_t...        113      2
113   /project/6008051/pone_simulation/MC000004-nu_t...        114      2
114   /project/6008051/pone_simulation/MC000004-nu_t...        115      2
115   /project/6008051/pone_simulation/MC000004-nu_t...        116      2
116   /project/6008051/pone_simulation/MC000004-nu_t...        117      2
117   /project/6008051/pone_simulation/MC000004-nu_t...        118      2
118   /project/6008051/pone_simulation/MC000004-nu_t...        119      2
119   /project/6008051/pone_simulation/MC000004-nu_t...        120      2
120   /project/6008051/pone_simulation/MC000004-nu_t...        121      2
121   /project/6008051/pone_simulation/MC000004-nu_t...        122      2
122   /project/6008051/pone_simulation/MC000004-nu_t...        123      2
123   /project/6008051/pone_simulation/MC000004-nu_t...        124      2
124   /project/6008051/pone_simulation/MC000004-nu_t...        125      2
125   /project/6008051/pone_simulation/MC000004-nu_t...        126      2
126   /project/6008051/pone_simulation/MC000004-nu_t...        127      2
127   /project/6008051/pone_simulation/MC000004-nu_t...        128      2
128   /project/6008051/pone_simulation/MC000004-nu_t...        129      2
129   /project/6008051/pone_simulation/MC000004-nu_t...        130      2
130   /project/6008051/pone_simulation/MC000004-nu_t...        131      2
131   /project/6008051/pone_simulation/MC000004-nu_t...        132      2
132   /project/6008051/pone_simulation/MC000004-nu_t...        133      2
133   /project/6008051/pone_simulation/MC000004-nu_t...        134      2
134   /project/6008051/pone_simulation/MC000004-nu_t...        135      2
135   /project/6008051/pone_simulation/MC000004-nu_t...        136      2
136   /project/6008051/pone_simulation/MC000004-nu_t...        137      2
137   /project/6008051/pone_simulation/MC000004-nu_t...        138      2
138   /project/6008051/pone_simulation/MC000004-nu_t...        139      2
139   /project/6008051/pone_simulation/MC000004-nu_t...        140      2
140   /project/6008051/pone_simulation/MC000004-nu_t...        141      2
141   /project/6008051/pone_simulation/MC000004-nu_t...        142      2
142   /project/6008051/pone_simulation/MC000004-nu_t...        143      2
143   /project/6008051/pone_simulation/MC000004-nu_t...        144      2
144   /project/6008051/pone_simulation/MC000004-nu_t...        145      2
145   /project/6008051/pone_simulation/MC000004-nu_t...        146      2
146   /project/6008051/pone_simulation/MC000004-nu_t...        147      2
147   /project/6008051/pone_simulation/MC000004-nu_t...        148      2
148   /project/6008051/pone_simulation/MC000004-nu_t...        149      2
149   /project/6008051/pone_simulation/MC000004-nu_t...        150      2
150   /project/6008051/pone_simulation/MC000004-nu_t...        151      2
151   /project/6008051/pone_simulation/MC000004-nu_t...        152      2
152   /project/6008051/pone_simulation/MC000004-nu_t...        153      2
153   /project/6008051/pone_simulation/MC000004-nu_t...        154      2
154   /project/6008051/pone_simulation/MC000004-nu_t...        155      2
155   /project/6008051/pone_simulation/MC000004-nu_t...        156      2
156   /project/6008051/pone_simulation/MC000004-nu_t...        157      2
157   /project/6008051/pone_simulation/MC000004-nu_t...        158      2
158   /project/6008051/pone_simulation/MC000004-nu_t...        159      2
159   /project/6008051/pone_simulation/MC000004-nu_t...        160      2
160   /project/6008051/pone_simulation/MC000004-nu_t...        161      2
161   /project/6008051/pone_simulation/MC000004-nu_t...        162      2
162   /project/6008051/pone_simulation/MC000004-nu_t...        163      2
163   /project/6008051/pone_simulation/MC000004-nu_t...        164      2
164   /project/6008051/pone_simulation/MC000004-nu_t...        165      2
165   /project/6008051/pone_simulation/MC000004-nu_t...        166      2
166   /project/6008051/pone_simulation/MC000004-nu_t...        167      2
167   /project/6008051/pone_simulation/MC000004-nu_t...        168      2
168   /project/6008051/pone_simulation/MC000004-nu_t...        169      2
169   /project/6008051/pone_simulation/MC000004-nu_t...        170      2
170   /project/6008051/pone_simulation/MC000004-nu_t...        171      2
171   /project/6008051/pone_simulation/MC000004-nu_t...        172      2
172   /project/6008051/pone_simulation/MC000004-nu_t...        173      2
173   /project/6008051/pone_simulation/MC000004-nu_t...        174      2
174   /project/6008051/pone_simulation/MC000004-nu_t...        175      2
175   /project/6008051/pone_simulation/MC000004-nu_t...        176      2
176   /project/6008051/pone_simulation/MC000004-nu_t...        177      2
177   /project/6008051/pone_simulation/MC000004-nu_t...        178      2
178   /project/6008051/pone_simulation/MC000004-nu_t...        179      2
179   /project/6008051/pone_simulation/MC000004-nu_t...        180      2
180   /project/6008051/pone_simulation/MC000004-nu_t...        181      2
181   /project/6008051/pone_simulation/MC000004-nu_t...        182      2
182   /project/6008051/pone_simulation/MC000004-nu_t...        183      2
183   /project/6008051/pone_simulation/MC000004-nu_t...        184      2
184   /project/6008051/pone_simulation/MC000004-nu_t...        185      2
185   /project/6008051/pone_simulation/MC000004-nu_t...        186      2
186   /project/6008051/pone_simulation/MC000004-nu_t...        187      2
187   /project/6008051/pone_simulation/MC000004-nu_t...        188      2
188   /project/6008051/pone_simulation/MC000004-nu_t...        189      2
189   /project/6008051/pone_simulation/MC000004-nu_t...        190      2
190   /project/6008051/pone_simulation/MC000004-nu_t...        191      2
191   /project/6008051/pone_simulation/MC000004-nu_t...        192      2
192   /project/6008051/pone_simulation/MC000004-nu_t...        193      2
193   /project/6008051/pone_simulation/MC000004-nu_t...        194      2
194   /project/6008051/pone_simulation/MC000004-nu_t...        195      2
195   /project/6008051/pone_simulation/MC000004-nu_t...        196      2
196   /project/6008051/pone_simulation/MC000004-nu_t...        197      2
197   /project/6008051/pone_simulation/MC000004-nu_t...        198      2
198   /project/6008051/pone_simulation/MC000004-nu_t...        199      2
199   /project/6008051/pone_simulation/MC000004-nu_t...        200      2
200   /project/6008051/pone_simulation/MC000004-nu_t...          1      8
201   /project/6008051/pone_simulation/MC000004-nu_t...          2      8
202   /project/6008051/pone_simulation/MC000004-nu_t...          3      8
203   /project/6008051/pone_simulation/MC000004-nu_t...          4      8
204   /project/6008051/pone_simulation/MC000004-nu_t...          5      8
205   /project/6008051/pone_simulation/MC000004-nu_t...          6      8
206   /project/6008051/pone_simulation/MC000004-nu_t...          7      8
207   /project/6008051/pone_simulation/MC000004-nu_t...          8      8
208   /project/6008051/pone_simulation/MC000004-nu_t...          9      8
209   /project/6008051/pone_simulation/MC000004-nu_t...         10      8
210   /project/6008051/pone_simulation/MC000004-nu_t...         11      8
211   /project/6008051/pone_simulation/MC000004-nu_t...         12      8
212   /project/6008051/pone_simulation/MC000004-nu_t...         13      8
213   /project/6008051/pone_simulation/MC000004-nu_t...         14      8
214   /project/6008051/pone_simulation/MC000004-nu_t...         15      8
215   /project/6008051/pone_simulation/MC000004-nu_t...         16      8
216   /project/6008051/pone_simulation/MC000004-nu_t...         17      8
217   /project/6008051/pone_simulation/MC000004-nu_t...         18      8
218   /project/6008051/pone_simulation/MC000004-nu_t...         19      8
219   /project/6008051/pone_simulation/MC000004-nu_t...         20      8
220   /project/6008051/pone_simulation/MC000004-nu_t...         21      8
221   /project/6008051/pone_simulation/MC000004-nu_t...         22      8
222   /project/6008051/pone_simulation/MC000004-nu_t...         23      8
223   /project/6008051/pone_simulation/MC000004-nu_t...         24      8
224   /project/6008051/pone_simulation/MC000004-nu_t...         25      8
225   /project/6008051/pone_simulation/MC000004-nu_t...         26      8
226   /project/6008051/pone_simulation/MC000004-nu_t...         27      8
227   /project/6008051/pone_simulation/MC000004-nu_t...         28      8
228   /project/6008051/pone_simulation/MC000004-nu_t...         29      8
229   /project/6008051/pone_simulation/MC000004-nu_t...         30      8
230   /project/6008051/pone_simulation/MC000004-nu_t...         31      8
231   /project/6008051/pone_simulation/MC000004-nu_t...         32      8
232   /project/6008051/pone_simulation/MC000004-nu_t...         33      8
233   /project/6008051/pone_simulation/MC000004-nu_t...         34      8
234   /project/6008051/pone_simulation/MC000004-nu_t...         35      8
235   /project/6008051/pone_simulation/MC000004-nu_t...         36      8
236   /project/6008051/pone_simulation/MC000004-nu_t...         37      8
237   /project/6008051/pone_simulation/MC000004-nu_t...         38      8
238   /project/6008051/pone_simulation/MC000004-nu_t...         39      8
239   /project/6008051/pone_simulation/MC000004-nu_t...         40      8
240   /project/6008051/pone_simulation/MC000004-nu_t...         41      8
241   /project/6008051/pone_simulation/MC000004-nu_t...         42      8
242   /project/6008051/pone_simulation/MC000004-nu_t...         43      8
243   /project/6008051/pone_simulation/MC000004-nu_t...         44      8
244   /project/6008051/pone_simulation/MC000004-nu_t...         45      8
245   /project/6008051/pone_simulation/MC000004-nu_t...         46      8
246   /project/6008051/pone_simulation/MC000004-nu_t...         47      8
247   /project/6008051/pone_simulation/MC000004-nu_t...         48      8
248   /project/6008051/pone_simulation/MC000004-nu_t...         49      8
249   /project/6008051/pone_simulation/MC000004-nu_t...         50      8
250   /project/6008051/pone_simulation/MC000004-nu_t...         51      8
251   /project/6008051/pone_simulation/MC000004-nu_t...         52      8
252   /project/6008051/pone_simulation/MC000004-nu_t...         53      8
253   /project/6008051/pone_simulation/MC000004-nu_t...         54      8
254   /project/6008051/pone_simulation/MC000004-nu_t...         55      8
255   /project/6008051/pone_simulation/MC000004-nu_t...         56      8
256   /project/6008051/pone_simulation/MC000004-nu_t...         57      8
257   /project/6008051/pone_simulation/MC000004-nu_t...         58      8
258   /project/6008051/pone_simulation/MC000004-nu_t...         59      8
259   /project/6008051/pone_simulation/MC000004-nu_t...         60      8
260   /project/6008051/pone_simulation/MC000004-nu_t...         61      8
261   /project/6008051/pone_simulation/MC000004-nu_t...         62      8
262   /project/6008051/pone_simulation/MC000004-nu_t...         63      8
263   /project/6008051/pone_simulation/MC000004-nu_t...         64      8
264   /project/6008051/pone_simulation/MC000004-nu_t...         65      8
265   /project/6008051/pone_simulation/MC000004-nu_t...         66      8
266   /project/6008051/pone_simulation/MC000004-nu_t...         67      8
267   /project/6008051/pone_simulation/MC000004-nu_t...         68      8
268   /project/6008051/pone_simulation/MC000004-nu_t...         69      8

In [5]:
print(f"total DAQ/EventProperties rows = {len(raw_event_properties_df)}")
print(f"unique RunID count = {raw_event_properties_df['RunID'].nunique()}")
print(f"unique EventID count = {raw_event_properties_df[['RunID', 'EventID', 'SubEventID']].drop_duplicates().shape[0]}")

for column in ["finalType1", "finalType2", "initialType"]:
    values = raw_event_properties_df[column].drop_duplicates().tolist()
    print(f"\nunique {column} ({len(values)}):")
    print(values)

total DAQ/EventProperties rows = 2200
unique RunID count = 11
unique EventID count = 2200

unique finalType1 (2):
[-12, 12]

unique finalType2 (1):
[-2000001006]

unique initialType (2):
[-12, 12]

to move:

mv /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_002.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_008.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_009.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_011.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_012.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_208.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_224.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_326.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_335.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_707.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Tau_PMT_Response/tau_gen_929.i3.gz /home/kbas/scratch/String340MC/Full_Geometry/Electron_PMT_Response/

to move

mv /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_002.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_008.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_009.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_011.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_012.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_208.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_224.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_326.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_335.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_707.i3.gz /home/kbas/scratch/String340MC/102_string/Tau_PMT_Response/tau_tau_gen_929.i3.gz /home/kbas/scratch/String340MC/102_string/Electron_PMT_Response/