knk unique eventleri bi kontrol et.
bos olanlar drop ediliyo mu bak.
eski tanima gore olan event id tanimi ile yenisi arasinda cakisma var mi


knkkkkk tum paqeuetler bitince bunu bir validity check scripti olarak yap

In [8]:
import polars as pl

features_000_path = "/home/kbas/scratch/String340MC/102_string/Electron_Parquet/features/electron_electron_gen_000_features.parquet"
features_001_path = "/home/kbas/scratch/String340MC/102_string/Electron_Parquet/features/electron_electron_gen_001_features.parquet"

truth_000_path = "/home/kbas/scratch/String340MC/102_string/Electron_Parquet/truth/electron_electron_gen_000_truth.parquet"
truth_001_path = "/home/kbas/scratch/String340MC/102_string/Electron_Parquet/truth/electron_electron_gen_001_truth.parquet"

features_000 = pl.read_parquet(features_000_path)
features_001 = pl.read_parquet(features_001_path)

truth_000 = pl.read_parquet(truth_000_path)
truth_001 = pl.read_parquet(truth_001_path)

print("features_000")
display(features_000.head())

print("features_001")
display(features_001.head())

print("truth_000")
display(truth_000.head())

print("truth_001")
display(truth_001.head())

features_000

shape: (5, 12)
┌──────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬──────────┐
│ charge   ┆ dom_time   ┆ dom_x ┆ dom_y      ┆ … ┆ pmt_x      ┆ pmt_y      ┆ pmt_z      ┆ event_no │
│ ---      ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ f64      ┆ f64        ┆ f64   ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ i64      │
╞══════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪══════════╡
│ 1.012924 ┆ 2435.41736 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 40.116003  ┆ -37.715556 ┆ -400.0     ┆ 50       │
│          ┆ 7          ┆       ┆            ┆   ┆            ┆            ┆            ┆          │
│ 1.088672 ┆ 2328.58076 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 40.0       ┆ -37.715556 ┆ -350.11600 ┆ 50       │
│          ┆ 8          ┆       ┆            ┆   ┆            ┆            ┆ 3          ┆          │
│ 1.249784 ┆ 2324.72812 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 39.861639  ┆ -37.806401 ┆ -350.13836 ┆ 50       │
│          ┆ 5          ┆       ┆            ┆   ┆            ┆            ┆ 1          ┆          │
│ 0.785984 ┆ 2271.86120 ┆ 0.0   ┆ 31.384388  ┆ … ┆ -2.1309e-1 ┆ 31.566476  ┆ -399.88399 ┆ 50       │
│          ┆ 2          ┆       ┆            ┆   ┆ 7          ┆            ┆ 7          ┆          │
│ 1.114951 ┆ 2046.34535 ┆ 0.0   ┆ 31.384388  ┆ … ┆ -2.1309e-1 ┆ 31.566476  ┆ -349.88399 ┆ 50       │
│          ┆ 5          ┆       ┆            ┆   ┆ 7          ┆            ┆ 7          ┆          │
└──────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴──────────┘

features_001

shape: (5, 12)
┌──────────┬────────────┬────────┬───────────┬───┬────────────┬────────────┬────────────┬──────────┐
│ charge   ┆ dom_time   ┆ dom_x  ┆ dom_y     ┆ … ┆ pmt_x      ┆ pmt_y      ┆ pmt_z      ┆ event_no │
│ ---      ┆ ---        ┆ ---    ┆ ---       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ f64      ┆ f64        ┆ f64    ┆ f64       ┆   ┆ f64        ┆ f64        ┆ f64        ┆ i64      │
╞══════════╪════════════╪════════╪═══════════╪═══╪════════════╪════════════╪════════════╪══════════╡
│ 1.04652  ┆ 2344.84943 ┆ -320.0 ┆ 31.384388 ┆ … ┆ -319.86163 ┆ 31.293144  ┆ 249.861639 ┆ 20       │
│          ┆ 2          ┆        ┆           ┆   ┆ 9          ┆            ┆            ┆          │
│ 0.386276 ┆ 2282.08316 ┆ -240.0 ┆ 31.384388 ┆ … ┆ -240.11600 ┆ 31.566476  ┆ 200.0      ┆ 20       │
│          ┆ 5          ┆        ┆           ┆   ┆ 3          ┆            ┆            ┆          │
│ 0.815611 ┆ 2323.99905 ┆ -280.0 ┆ 100.66642 ┆ … ┆ -279.88399 ┆ 100.848508 ┆ 150.0      ┆ 20       │
│          ┆ 8          ┆        ┆           ┆   ┆ 7          ┆            ┆            ┆          │
│ 1.204929 ┆ 2363.46351 ┆ -280.0 ┆ 100.66642 ┆ … ┆ -280.0     ┆ 100.848508 ┆ 149.883997 ┆ 20       │
│          ┆ 5          ┆        ┆           ┆   ┆            ┆            ┆            ┆          │
│ 0.705896 ┆ 2331.58555 ┆ -280.0 ┆ 100.66642 ┆ … ┆ -280.13836 ┆ 100.757663 ┆ 150.138361 ┆ 20       │
│          ┆ 6          ┆        ┆           ┆   ┆ 1          ┆            ┆            ┆          │
└──────────┴────────────┴────────┴───────────┴───┴────────────┴────────────┴────────────┴──────────┘

truth_000

shape: (5, 26)
┌───────┬────────────┬─────────┬────────────┬───┬──────────────┬─────────────┬──────────┬──────────┐
│ RunID ┆ SubrunID   ┆ EventID ┆ SubEventID ┆ … ┆ through_goin ┆ missed_trac ┆ is_track ┆ event_no │
│ ---   ┆ ---        ┆ ---     ┆ ---        ┆   ┆ g            ┆ k           ┆ ---      ┆ ---      │
│ i64   ┆ i64        ┆ i64     ┆ i64        ┆   ┆ ---          ┆ ---         ┆ i64      ┆ i64      │
│       ┆            ┆         ┆            ┆   ┆ i64          ┆ i64         ┆          ┆          │
╞═══════╪════════════╪═════════╪════════════╪═══╪══════════════╪═════════════╪══════════╪══════════╡
│ 0     ┆ 4294967295 ┆ 36      ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 50       │
│ 0     ┆ 4294967295 ┆ 86      ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 51       │
│ 0     ┆ 4294967295 ┆ 117     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 52       │
│ 0     ┆ 4294967295 ┆ 118     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 53       │
│ 0     ┆ 4294967295 ┆ 138     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 54       │
└───────┴────────────┴─────────┴────────────┴───┴──────────────┴─────────────┴──────────┴──────────┘

truth_001

shape: (5, 26)
┌───────┬────────────┬─────────┬────────────┬───┬──────────────┬─────────────┬──────────┬──────────┐
│ RunID ┆ SubrunID   ┆ EventID ┆ SubEventID ┆ … ┆ through_goin ┆ missed_trac ┆ is_track ┆ event_no │
│ ---   ┆ ---        ┆ ---     ┆ ---        ┆   ┆ g            ┆ k           ┆ ---      ┆ ---      │
│ i64   ┆ i64        ┆ i64     ┆ i64        ┆   ┆ ---          ┆ ---         ┆ i64      ┆ i64      │
│       ┆            ┆         ┆            ┆   ┆ i64          ┆ i64         ┆          ┆          │
╞═══════╪════════════╪═════════╪════════════╪═══╪══════════════╪═════════════╪══════════╪══════════╡
│ 1     ┆ 4294967295 ┆ 42      ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 20       │
│ 1     ┆ 4294967295 ┆ 81      ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 21       │
│ 1     ┆ 4294967295 ┆ 103     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 22       │
│ 1     ┆ 4294967295 ┆ 162     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 23       │
│ 1     ┆ 4294967295 ┆ 176     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 24       │
└───────┴────────────┴─────────┴────────────┴───┴──────────────┴─────────────┴──────────┴──────────┘

In [9]:
for name, df in {
    "features_000": features_000,
    "features_001": features_001,
    "truth_000": truth_000,
    "truth_001": truth_001,
}.items():
    print(f"\n{name}: shape={df.shape}")
    print(df.schema)

features_000: shape=(208, 12)
Schema({'charge': Float64, 'dom_time': Float64, 'dom_x': Float64, 'dom_y': Float64, 'dom_z': Float64, 'string_number': Int64, 'pmt_number': Int64, 'dom_number': Int64, 'pmt_x': Float64, 'pmt_y': Float64, 'pmt_z': Float64, 'event_no': Int64})

features_001: shape=(782, 12)
Schema({'charge': Float64, 'dom_time': Float64, 'dom_x': Float64, 'dom_y': Float64, 'dom_z': Float64, 'string_number': Int64, 'pmt_number': Int64, 'dom_number': Int64, 'pmt_x': Float64, 'pmt_y': Float64, 'pmt_z': Float64, 'event_no': Int64})

truth_000: shape=(5, 26)
Schema({'RunID': Int64, 'SubrunID': Int64, 'EventID': Int64, 'SubEventID': Int64, 'position_x': Float64, 'position_y': Float64, 'position_z': Float64, 'pid': Int64, 'interaction_type': Int64, 'totalEnergy': Float64, 'zenith': Float64, 'azimuth': Float64, 'finalStateX': Float64, 'finalStateY': Float64, 'finalType1': Int64, 'finalType2': Int64, 'initialType': Int64, 'totalColumnDepth': Float64, 'impactParameter': Float64, 'fully_contained': Int64, 'starting_track': Int64, 'stopping_track': Int64, 'through_going': Int64, 'missed_track': Int64, 'is_track': Int64, 'event_no': Int64})

truth_001: shape=(6, 26)
Schema({'RunID': Int64, 'SubrunID': Int64, 'EventID': Int64, 'SubEventID': Int64, 'position_x': Float64, 'position_y': Float64, 'position_z': Float64, 'pid': Int64, 'interaction_type': Int64, 'totalEnergy': Float64, 'zenith': Float64, 'azimuth': Float64, 'finalStateX': Float64, 'finalStateY': Float64, 'finalType1': Int64, 'finalType2': Int64, 'initialType': Int64, 'totalColumnDepth': Float64, 'impactParameter': Float64, 'fully_contained': Int64, 'starting_track': Int64, 'stopping_track': Int64, 'through_going': Int64, 'missed_track': Int64, 'is_track': Int64, 'event_no': Int64})

In [10]:
features_000.filter(pl.col("event_no") > 0).head()

shape: (5, 12)
┌──────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬──────────┐
│ charge   ┆ dom_time   ┆ dom_x ┆ dom_y      ┆ … ┆ pmt_x      ┆ pmt_y      ┆ pmt_z      ┆ event_no │
│ ---      ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ f64      ┆ f64        ┆ f64   ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ i64      │
╞══════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪══════════╡
│ 1.012924 ┆ 2435.41736 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 40.116003  ┆ -37.715556 ┆ -400.0     ┆ 50       │
│          ┆ 7          ┆       ┆            ┆   ┆            ┆            ┆            ┆          │
│ 1.088672 ┆ 2328.58076 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 40.0       ┆ -37.715556 ┆ -350.11600 ┆ 50       │
│          ┆ 8          ┆       ┆            ┆   ┆            ┆            ┆ 3          ┆          │
│ 1.249784 ┆ 2324.72812 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 39.861639  ┆ -37.806401 ┆ -350.13836 ┆ 50       │
│          ┆ 5          ┆       ┆            ┆   ┆            ┆            ┆ 1          ┆          │
│ 0.785984 ┆ 2271.86120 ┆ 0.0   ┆ 31.384388  ┆ … ┆ -2.1309e-1 ┆ 31.566476  ┆ -399.88399 ┆ 50       │
│          ┆ 2          ┆       ┆            ┆   ┆ 7          ┆            ┆ 7          ┆          │
│ 1.114951 ┆ 2046.34535 ┆ 0.0   ┆ 31.384388  ┆ … ┆ -2.1309e-1 ┆ 31.566476  ┆ -349.88399 ┆ 50       │
│          ┆ 5          ┆       ┆            ┆   ┆ 7          ┆            ┆ 7          ┆          │
└──────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴──────────┘

In [11]:
for name, f, t in [
    ("000", features_000, truth_000),
    ("001", features_001, truth_001),
]:
    print(
        name,
        "truth rows =", t.height,
        "| feature unique event_no =",
        f["event_no"].n_unique(),
    )

000 truth rows = 5 | feature unique event_no = 5
001 truth rows = 6 | feature unique event_no = 6

In [12]:
import pandas as pd
import polars as pl
import pyarrow.parquet as pq

paths = {
    "features_000": "/home/kbas/scratch/String340MC/102_string/Electron_Parquet/features/electron_electron_gen_000_features.parquet",
    "truth_000": "/home/kbas/scratch/String340MC/102_string/Electron_Parquet/truth/electron_electron_gen_000_truth.parquet",
}

for name, path in paths.items():
    print("\n" + "=" * 80)
    print(name)
    print(path)

    pdf = pd.read_parquet(path)
    print("\n[pandas]")
    print("shape:", pdf.shape)
    print("columns:", list(pdf.columns))
    print("index name:", pdf.index.name)
    print("index sample:", pdf.index[:10].tolist())
    print(pdf.head())

    pldf = pl.read_parquet(path)
    print("\n[polars]")
    print("shape:", pldf.shape)
    print("columns:", pldf.columns)
    print(pldf.head())

    print("\n[pyarrow physical schema]")
    print(pq.read_schema(path))

================================================================================
features_000
/home/kbas/scratch/String340MC/102_string/Electron_Parquet/features/electron_electron_gen_000_features.parquet

[pandas]
shape: (208, 11)
columns: ['charge', 'dom_time', 'dom_x', 'dom_y', 'dom_z', 'string_number', 'pmt_number', 'dom_number', 'pmt_x', 'pmt_y', 'pmt_z']
index name: event_no
index sample: [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]
            charge     dom_time  dom_x      dom_y  dom_z  string_number  \
event_no
50        1.012924  2435.417367   40.0 -37.897645 -400.0            161
50        1.088672  2328.580768   40.0 -37.897645 -350.0            161
50        1.249784  2324.728125   40.0 -37.897645 -350.0            161
50        0.785984  2271.861202    0.0  31.384388 -400.0            180
50        1.114951  2046.345355    0.0  31.384388 -350.0            180

          pmt_number  dom_number         pmt_x      pmt_y       pmt_z
event_no
50                 2           2  4.011600e+01 -37.715556 -400.000000
50                 3           3  4.000000e+01 -37.715556 -350.116003
50                 8           3  3.986164e+01 -37.806401 -350.138361
50                 1           2 -2.130940e-17  31.566476 -399.883997
50                 1           3 -2.130940e-17  31.566476 -349.883997

[polars]
shape: (208, 12)
columns: ['charge', 'dom_time', 'dom_x', 'dom_y', 'dom_z', 'string_number', 'pmt_number', 'dom_number', 'pmt_x', 'pmt_y', 'pmt_z', 'event_no']
shape: (5, 12)
┌──────────┬────────────┬───────┬────────────┬───┬────────────┬────────────┬────────────┬──────────┐
│ charge   ┆ dom_time   ┆ dom_x ┆ dom_y      ┆ … ┆ pmt_x      ┆ pmt_y      ┆ pmt_z      ┆ event_no │
│ ---      ┆ ---        ┆ ---   ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---      │
│ f64      ┆ f64        ┆ f64   ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ i64      │
╞══════════╪════════════╪═══════╪════════════╪═══╪════════════╪════════════╪════════════╪══════════╡
│ 1.012924 ┆ 2435.41736 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 40.116003  ┆ -37.715556 ┆ -400.0     ┆ 50       │
│          ┆ 7          ┆       ┆            ┆   ┆            ┆            ┆            ┆          │
│ 1.088672 ┆ 2328.58076 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 40.0       ┆ -37.715556 ┆ -350.11600 ┆ 50       │
│          ┆ 8          ┆       ┆            ┆   ┆            ┆            ┆ 3          ┆          │
│ 1.249784 ┆ 2324.72812 ┆ 40.0  ┆ -37.897645 ┆ … ┆ 39.861639  ┆ -37.806401 ┆ -350.13836 ┆ 50       │
│          ┆ 5          ┆       ┆            ┆   ┆            ┆            ┆ 1          ┆          │
│ 0.785984 ┆ 2271.86120 ┆ 0.0   ┆ 31.384388  ┆ … ┆ -2.1309e-1 ┆ 31.566476  ┆ -399.88399 ┆ 50       │
│          ┆ 2          ┆       ┆            ┆   ┆ 7          ┆            ┆ 7          ┆          │
│ 1.114951 ┆ 2046.34535 ┆ 0.0   ┆ 31.384388  ┆ … ┆ -2.1309e-1 ┆ 31.566476  ┆ -349.88399 ┆ 50       │
│          ┆ 5          ┆       ┆            ┆   ┆ 7          ┆            ┆ 7          ┆          │
└──────────┴────────────┴───────┴────────────┴───┴────────────┴────────────┴────────────┴──────────┘

[pyarrow physical schema]
charge: double
dom_time: double
dom_x: double
dom_y: double
dom_z: double
string_number: int64
pmt_number: int64
dom_number: int64
pmt_x: double
pmt_y: double
pmt_z: double
event_no: int64
-- schema metadata --
pandas: '{"index_columns": ["event_no"], "column_indexes": [{"name": null' + 1585

================================================================================
truth_000
/home/kbas/scratch/String340MC/102_string/Electron_Parquet/truth/electron_electron_gen_000_truth.parquet

[pandas]
shape: (5, 25)
columns: ['RunID', 'SubrunID', 'EventID', 'SubEventID', 'position_x', 'position_y', 'position_z', 'pid', 'interaction_type', 'totalEnergy', 'zenith', 'azimuth', 'finalStateX', 'finalStateY', 'finalType1', 'finalType2', 'initialType', 'totalColumnDepth', 'impactParameter', 'fully_contained', 'starting_track', 'stopping_track', 'through_going', 'missed_track', 'is_track']
index name: event_no
index sample: [50, 51, 52, 53, 54]
          RunID    SubrunID  EventID  SubEventID  position_x  position_y  \
event_no
50            0  4294967295       36           0   17.596688   62.474206
51            0  4294967295       86           0  568.133293  214.791809
52            0  4294967295      117           0  315.750737  -11.870211
53            0  4294967295      118           0 -274.595485  184.913049
54            0  4294967295      138           0 -647.577477 -296.804320

          position_z  pid  interaction_type  totalEnergy  ...  finalType2  \
event_no                                                  ...
50       -312.796274   12                 1   685.877118  ... -2000001006
51        322.375026   12                 1  1503.471867  ... -2000001006
52         79.847698  -12                 1   184.394663  ... -2000001006
53         29.720297  -12                 1   514.298343  ... -2000001006
54        369.515815  -12                 1   270.983892  ... -2000001006

          initialType  totalColumnDepth  impactParameter  fully_contained  \
event_no
50                 12     439943.488988       160.156171               -1
51                 12     482657.146981       484.238027               -1
52                -12     313747.892870        94.812960               -1
53                -12     479103.631557       286.000322               -1
54                -12     450114.388842       281.610051               -1

          starting_track  stopping_track  through_going  missed_track  \
event_no
50                    -1              -1             -1            -1
51                    -1              -1             -1            -1
52                    -1              -1             -1            -1
53                    -1              -1             -1            -1
54                    -1              -1             -1            -1

          is_track
event_no
50               0
51               0
52               0
53               0
54               0

[5 rows x 25 columns]

[polars]
shape: (5, 26)
columns: ['RunID', 'SubrunID', 'EventID', 'SubEventID', 'position_x', 'position_y', 'position_z', 'pid', 'interaction_type', 'totalEnergy', 'zenith', 'azimuth', 'finalStateX', 'finalStateY', 'finalType1', 'finalType2', 'initialType', 'totalColumnDepth', 'impactParameter', 'fully_contained', 'starting_track', 'stopping_track', 'through_going', 'missed_track', 'is_track', 'event_no']
shape: (5, 26)
┌───────┬────────────┬─────────┬────────────┬───┬──────────────┬─────────────┬──────────┬──────────┐
│ RunID ┆ SubrunID   ┆ EventID ┆ SubEventID ┆ … ┆ through_goin ┆ missed_trac ┆ is_track ┆ event_no │
│ ---   ┆ ---        ┆ ---     ┆ ---        ┆   ┆ g            ┆ k           ┆ ---      ┆ ---      │
│ i64   ┆ i64        ┆ i64     ┆ i64        ┆   ┆ ---          ┆ ---         ┆ i64      ┆ i64      │
│       ┆            ┆         ┆            ┆   ┆ i64          ┆ i64         ┆          ┆          │
╞═══════╪════════════╪═════════╪════════════╪═══╪══════════════╪═════════════╪══════════╪══════════╡
│ 0     ┆ 4294967295 ┆ 36      ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 50       │
│ 0     ┆ 4294967295 ┆ 86      ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 51       │
│ 0     ┆ 4294967295 ┆ 117     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 52       │
│ 0     ┆ 4294967295 ┆ 118     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 53       │
│ 0     ┆ 4294967295 ┆ 138     ┆ 0          ┆ … ┆ -1           ┆ -1          ┆ 0        ┆ 54       │
└───────┴────────────┴─────────┴────────────┴───┴──────────────┴─────────────┴──────────┴──────────┘

[pyarrow physical schema]
RunID: int64
SubrunID: int64
EventID: int64
SubEventID: int64
position_x: double
position_y: double
position_z: double
pid: int64
interaction_type: int64
totalEnergy: double
zenith: double
azimuth: double
finalStateX: double
finalStateY: double
finalType1: int64
finalType2: int64
initialType: int64
totalColumnDepth: double
impactParameter: double
fully_contained: int64
starting_track: int64
stopping_track: int64
through_going: int64
missed_track: int64
is_track: int64
event_no: int64
-- schema metadata --
pandas: '{"index_columns": ["event_no"], "column_indexes": [{"name": null' + 3323

In [15]:
pairs = [
    ("000", features_000, truth_000),
    ("001", features_001, truth_001),
]

for name, f, t in pairs:
    f_ids = set(f["event_no"].unique().to_list())
    t_ids = set(t["event_no"].unique().to_list())

    print(f"\n{name}")
    print("feature unique:", len(f_ids))
    print("truth unique  :", len(t_ids))
    print("same ids      :", f_ids == t_ids)

    if f_ids != t_ids:
        print("in features not truth:", sorted(f_ids - t_ids)[:20])
        print("in truth not features:", sorted(t_ids - f_ids)[:20])

000
feature unique: 5
truth unique  : 5
same ids      : True

001
feature unique: 6
truth unique  : 6
same ids      : True

In [16]:
pairs = [
    ("000", features_000, truth_000),
    ("001", features_001, truth_001),
]

for name, f, t in pairs:
    f_ids = sorted(f["event_no"].unique().to_list())
    t_ids = sorted(t["event_no"].unique().to_list())

    print(f"\n{name}")
    print("feature ids:", f_ids)
    print("truth ids  :", t_ids)
    print("same ids   :", f_ids == t_ids)

000
feature ids: [50, 51, 52, 53, 54]
truth ids  : [50, 51, 52, 53, 54]
same ids   : True

001
feature ids: [20, 21, 22, 23, 24, 25]
truth ids  : [20, 21, 22, 23, 24, 25]
same ids   : True

In [17]:
for name, truth in [
    ("000", truth_000),
    ("001", truth_001),
]:
    print(f"\n{name}")

    # Her (RunID, EventID) ikilisi kaç farklı event_no'ya gidiyor?
    key_to_eventno = (
        truth
        .group_by(["RunID", "EventID"])
        .agg(pl.col("event_no").n_unique().alias("n_event_no"))
        .filter(pl.col("n_event_no") != 1)
    )

    # Her event_no kaç farklı (RunID, EventID) ikilisine gidiyor?
    eventno_to_key = (
        truth
        .group_by("event_no")
        .agg(
            pl.struct(["RunID", "EventID"]).n_unique().alias("n_run_event_pairs")
        )
        .filter(pl.col("n_run_event_pairs") != 1)
    )

    print("bad (RunID, EventID) -> event_no rows:", key_to_eventno.height)
    display(key_to_eventno)

    print("bad event_no -> (RunID, EventID) rows:", eventno_to_key.height)
    display(eventno_to_key)

    print(
        "unique (RunID, EventID):",
        truth.select(["RunID", "EventID"]).unique().height,
        "| unique event_no:",
        truth["event_no"].n_unique(),
        "| truth rows:",
        truth.height,
    )

000
bad (RunID, EventID) -> event_no rows: 0

shape: (0, 3)
┌───────┬─────────┬────────────┐
│ RunID ┆ EventID ┆ n_event_no │
│ ---   ┆ ---     ┆ ---        │
│ i64   ┆ i64     ┆ u32        │
╞═══════╪═════════╪════════════╡
└───────┴─────────┴────────────┘

bad event_no -> (RunID, EventID) rows: 0

shape: (0, 2)
┌──────────┬───────────────────┐
│ event_no ┆ n_run_event_pairs │
│ ---      ┆ ---               │
│ i64      ┆ u32               │
╞══════════╪═══════════════════╡
└──────────┴───────────────────┘

unique (RunID, EventID): 5 | unique event_no: 5 | truth rows: 5

001
bad (RunID, EventID) -> event_no rows: 0

shape: (0, 3)
┌───────┬─────────┬────────────┐
│ RunID ┆ EventID ┆ n_event_no │
│ ---   ┆ ---     ┆ ---        │
│ i64   ┆ i64     ┆ u32        │
╞═══════╪═════════╪════════════╡
└───────┴─────────┴────────────┘

bad event_no -> (RunID, EventID) rows: 0

shape: (0, 2)
┌──────────┬───────────────────┐
│ event_no ┆ n_run_event_pairs │
│ ---      ┆ ---               │
│ i64      ┆ u32               │
╞══════════╪═══════════════════╡
└──────────┴───────────────────┘

unique (RunID, EventID): 6 | unique event_no: 6 | truth rows: 6

In [18]:
for name, truth in [
    ("000", truth_000),
    ("001", truth_001),
]:
    check = (
        truth
        .group_by(["RunID", "EventID"])
        .agg(
            pl.col("event_no").unique().sort().alias("event_no_values"),
            pl.col("event_no").n_unique().alias("n_event_no"),
            pl.len().alias("n_rows"),
        )
        .sort(["RunID", "EventID"])
    )

    print(f"\n{name}")
    print("all groups have exactly one event_no:", (check["n_event_no"] == 1).all())

    display(check)

000
all groups have exactly one event_no: True

shape: (5, 5)
┌───────┬─────────┬─────────────────┬────────────┬────────┐
│ RunID ┆ EventID ┆ event_no_values ┆ n_event_no ┆ n_rows │
│ ---   ┆ ---     ┆ ---             ┆ ---        ┆ ---    │
│ i64   ┆ i64     ┆ list[i64]       ┆ u32        ┆ u32    │
╞═══════╪═════════╪═════════════════╪════════════╪════════╡
│ 0     ┆ 36      ┆ [50]            ┆ 1          ┆ 1      │
│ 0     ┆ 86      ┆ [51]            ┆ 1          ┆ 1      │
│ 0     ┆ 117     ┆ [52]            ┆ 1          ┆ 1      │
│ 0     ┆ 118     ┆ [53]            ┆ 1          ┆ 1      │
│ 0     ┆ 138     ┆ [54]            ┆ 1          ┆ 1      │
└───────┴─────────┴─────────────────┴────────────┴────────┘

001
all groups have exactly one event_no: True

shape: (6, 5)
┌───────┬─────────┬─────────────────┬────────────┬────────┐
│ RunID ┆ EventID ┆ event_no_values ┆ n_event_no ┆ n_rows │
│ ---   ┆ ---     ┆ ---             ┆ ---        ┆ ---    │
│ i64   ┆ i64     ┆ list[i64]       ┆ u32        ┆ u32    │
╞═══════╪═════════╪═════════════════╪════════════╪════════╡
│ 1     ┆ 42      ┆ [20]            ┆ 1          ┆ 1      │
│ 1     ┆ 81      ┆ [21]            ┆ 1          ┆ 1      │
│ 1     ┆ 103     ┆ [22]            ┆ 1          ┆ 1      │
│ 1     ┆ 162     ┆ [23]            ┆ 1          ┆ 1      │
│ 1     ┆ 176     ┆ [24]            ┆ 1          ┆ 1      │
│ 1     ┆ 185     ┆ [25]            ┆ 1          ┆ 1      │
└───────┴─────────┴─────────────────┴────────────┴────────┘

In [19]:
for name, truth in [
    ("000", truth_000),
    ("001", truth_001),
]:
    print(f"\n{name}")

    subrun_ids = truth["SubrunID"].unique().sort()
    subevent_ids = truth["SubEventID"].unique().sort()

    print("SubrunID unique values:")
    display(subrun_ids)

    print("SubEventID unique values:")
    display(subevent_ids)

    print("SubrunID single value:", subrun_ids.len() == 1)
    print("SubEventID single value:", subevent_ids.len() == 1)

000
SubrunID unique values:

shape: (1,)
Series: 'SubrunID' [i64]
[
	4294967295
]

SubEventID unique values:

shape: (1,)
Series: 'SubEventID' [i64]
[
	0
]

SubrunID single value: True
SubEventID single value: True

001
SubrunID unique values:

shape: (1,)
Series: 'SubrunID' [i64]
[
	4294967295
]

SubEventID unique values:

shape: (1,)
Series: 'SubEventID' [i64]
[
	0
]

SubrunID single value: True
SubEventID single value: True