In [1]:
from collections import Counter
import pandas as pd


from icecube import icetray, dataio, LeptonInjector

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

In [3]:
electron_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/Electron_file_stats.csv")
muon_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/Muon_file_stats.csv")
tau_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/Tau_file_stats.csv")
nc_log = pd.read_csv("/home/kbas/scratch/String340MC/Logs/LIW/NC_file_stats.csv")

# Files with 0 Frames

In [4]:
electron_log[electron_log["weights_calculated"] == 0]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
188,1080,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1080.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1080.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.035017
805,1641,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1641.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1641.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.039830
855,1687,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1687.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1687.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.029212
2594,354,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_354.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_354.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.032430
3759,5235,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5235.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5235.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001408
4543,6428,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6428.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6428.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001408
4676,6629,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6629.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6629.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.002553
6631,9619,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9619.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9619.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.014699

In [5]:
electron_log[electron_log["weights_calculated"] == 0]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
188,1080,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1080.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1080.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.035017
805,1641,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1641.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1641.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.039830
855,1687,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1687.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1687.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.029212
2594,354,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_354.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_354.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.032430
3759,5235,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5235.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5235.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001408
4543,6428,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6428.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6428.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001408
4676,6629,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6629.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6629.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.002553
6631,9619,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9619.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9619.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.014699

In [6]:
muon_log[muon_log["weights_calculated"] == 0]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
4957,546,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_546.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_546.i3,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.013210
5711,616,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_616.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_616.i3,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.030360
5844,6282,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_6282.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_6282.i3,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.025225
6654,706,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_706.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_706.i3,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.026115
7553,7930,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_7930.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_7930.i3,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001413

In [7]:
nc_log[nc_log["weights_calculated"] == 0]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
1569,2335,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_2335.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_2335.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001476
8961,9055,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_9055.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_9055.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001198

In [8]:
tau_log[tau_log["weights_calculated"] == 0]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
2,2,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_002.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_002.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.139922
4,4,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_004.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_004.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.139310
5,5,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_005.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_005.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.139343
8,8,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_008.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_008.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.138956
9,9,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_009.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_009.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.138651
11,11,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_011.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_011.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.163195
12,12,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_012.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_012.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.138964
1288,208,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_208.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_208.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.149925
1464,224,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_224.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_224.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.078215
2586,326,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_326.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_326.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.051010
2685,335,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_335.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_335.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.070629
3342,3950,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3950.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3950.i3.zst,skipped,input file is listed in paths.BAD_I3_FILES as no_daq_for_some_reason,False,skip_no_daq,0,0,0.001246
6773,707,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_707.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_707.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.085633
9215,929,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_929.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_929.i3.zst,not ok,weighting problem at event 1: oneweight could not be computed. 0 event weights were calculated before the problem. Error: Out of declared generation phase space. Impossible event.,True,not_a_bad_file,0,0,0.104399

except tau, all looks fine.

# Files with 0 < x < 200

In [9]:
electron_log[
    (electron_log["weights_calculated"] > 0) &
    (electron_log["weights_calculated"] < 200)
]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
265,1150,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1150.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1150.i3.zst,partially ok,processed only first 165 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,165,165,0.131393
641,1492,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1492.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1492.i3.zst,partially ok,processed only first 122 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,122,122,0.195040
1599,2363,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_2363.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_2363.i3.zst,partially ok,processed only first 99 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,99,99,0.533163
1644,2404,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_2404.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_2404.i3.zst,partially ok,processed only first 79 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,79,79,0.122213
1659,2418,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_2418.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_2418.i3.zst,partially ok,processed only first 117 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,117,117,0.089907
2077,2798,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_2798.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_2798.i3.zst,partially ok,processed only first 122 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,122,122,0.966816
2230,2959,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_2959.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_2959.i3.zst,partially ok,processed only first 158 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,158,158,0.173212
2344,3157,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3157.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3157.i3.zst,partially ok,processed only first 30 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,30,30,0.312493
2560,3491,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3491.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3491.i3.zst,partially ok,processed only first 169 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,169,169,0.134654
2822,3882,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3882.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3882.i3.zst,partially ok,processed only first 174 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,174,174,0.171599
2851,3930,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3930.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3930.i3.zst,partially ok,processed only first 140 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,140,140,0.068685
3185,4415,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_4415.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_4415.i3.zst,partially ok,processed only first 139 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,139,139,0.185401
3775,5257,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5257.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5257.i3.zst,partially ok,processed only first 127 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,127,127,0.128015
4196,590,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_590.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_590.i3.zst,partially ok,processed only first 23 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,23,23,0.029223
4249,5971,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5971.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5971.i3.zst,partially ok,processed only first 30 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,30,30,0.021324
4289,6044,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6044.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6044.i3.zst,partially ok,processed only first 32 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,32,32,0.022991
4949,703,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_703.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_703.i3.zst,partially ok,processed only first 8 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,8,8,0.143171
4977,7084,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7084.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7084.i3.zst,partially ok,processed only first 16 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,16,16,0.064370
5194,7383,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7383.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7383.i3.zst,partially ok,processed only first 55 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,55,55,0.092278
5271,7504,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7504.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7504.i3.zst,partially ok,processed only first 76 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,76,76,0.064519
5345,7615,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7615.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7615.i3.zst,partially ok,processed only first 121 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,121,121,0.072367
5401,771,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_771.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_771.i3.zst,partially ok,processed only first 49 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,49,49,0.039639
5694,8150,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_8150.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_8150.i3.zst,partially ok,processed only first 127 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,127,127,0.136191
5701,8164,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_8164.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_8164.i3.zst,partially ok,processed only first 152 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,152,152,0.114515
5741,8222,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_8222.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_8222.i3.zst,partially ok,processed only first 81 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,81,81,0.066296
6099,8779,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_8779.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_8779.i3.zst,partially ok,processed only first 18 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,18,18,0.044444
6114,880,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_880.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_880.i3.zst,partially ok,processed only first 119 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,119,119,0.065757
6426,9287,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9287.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9287.i3.zst,partially ok,processed only first 115 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,115,115,0.082104
6468,9361,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9361.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9361.i3.zst,partially ok,processed only first 96 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,96,96,0.095631
6722,976,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_976.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_976.i3.zst,partially ok,processed only first 133 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,133,133,0.299578
6808,989,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_989.lic,/project/6008051/pone_simulation/MC000003-nu_e-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_989.i3.zst,partially ok,processed only first 17 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,17,17,0.039927

In [10]:
tau_log[
    (tau_log["weights_calculated"] > 0) &
    (tau_log["weights_calculated"] < 200)
]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
116,1014,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1014.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1014.i3.zst,partially ok,processed only first 107 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,107,107,0.139521
368,1243,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1243.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1243.i3.zst,partially ok,processed only first 106 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,106,106,0.114273
719,1562,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_1562.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_1562.i3.zst,partially ok,processed only first 144 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,144,144,0.092983
1553,2320,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_2320.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_2320.i3.zst,partially ok,processed only first 76 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,76,76,0.034533
2426,3114,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3114.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3114.i3.zst,partially ok,processed only first 11 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,11,11,0.037238
2556,3232,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3232.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3232.i3.zst,partially ok,processed only first 182 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,182,182,0.110165
3022,3656,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3656.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3656.i3.zst,partially ok,processed only first 129 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,129,129,1.727036
3027,3660,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3660.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3660.i3.zst,partially ok,processed only first 12 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,12,12,0.103163
3351,3959,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_3959.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_3959.i3.zst,partially ok,processed only first 121 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,121,121,0.074205
3648,4229,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_4229.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_4229.i3.zst,partially ok,processed only first 137 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,137,137,0.141262
4129,4666,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_4666.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_4666.i3.zst,partially ok,processed only first 15 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,15,15,0.047770
4875,5344,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5344.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5344.i3.zst,partially ok,processed only first 89 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,89,89,0.104906
4989,5448,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5448.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5448.i3.zst,partially ok,processed only first 41 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,41,41,0.073315
5022,5478,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5478.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5478.i3.zst,partially ok,processed only first 94 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,94,94,0.136685
5350,5776,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5776.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5776.i3.zst,partially ok,processed only first 123 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,123,123,0.125606
5353,5779,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5779.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5779.i3.zst,partially ok,processed only first 122 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,122,122,0.144429
5496,5909,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_5909.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_5909.i3.zst,partially ok,processed only first 59 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,59,59,0.095081
5620,6021,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6021.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6021.i3.zst,partially ok,processed only first 132 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,132,132,0.063492
6219,6566,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6566.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6566.i3.zst,partially ok,processed only first 87 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,87,87,0.094206
6563,6879,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_6879.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_6879.i3.zst,partially ok,processed only first 8 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,8,8,0.089559
6900,7185,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7185.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7185.i3.zst,partially ok,processed only first 58 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,58,58,0.056695
6920,7203,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7203.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7203.i3.zst,partially ok,processed only first 76 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,76,76,0.122146
7198,7456,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7456.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7456.i3.zst,partially ok,processed only first 23 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,23,23,0.039297
7203,7460,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7460.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7460.i3.zst,partially ok,processed only first 95 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,95,95,0.079498
7698,7910,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_7910.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_7910.i3.zst,partially ok,processed only first 115 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,115,115,0.070948
7989,8175,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_8175.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_8175.i3.zst,partially ok,processed only first 109 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,109,109,0.755356
8364,8516,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_8516.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_8516.i3.zst,partially ok,processed only first 14 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,14,14,0.031649
8805,8917,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_8917.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_8917.i3.zst,partially ok,processed only first 55 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,55,55,0.050325
8964,9061,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9061.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9061.i3.zst,partially ok,processed only first 44 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,44,44,0.061498
9170,9249,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9249.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9249.i3.zst,partially ok,processed only first 31 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,31,31,0.048203
9302,9369,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9369.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9369.i3.zst,partially ok,processed only first 144 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,144,144,1.114822
9361,9422,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9422.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9422.i3.zst,partially ok,processed only first 63 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,63,63,0.051834
9467,9519,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9519.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9519.i3.zst,partially ok,processed only first 164 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,164,164,0.091077
9639,9675,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/genCard_9675.lic,/project/6008051/pone_simulation/MC000004-nu_tau-2_7-LeptonInjector_PROPOSAL_clsim-v10/Generator/gen_9675.i3.zst,partially ok,processed only first 169 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,169,169,0.148184

In [11]:
nc_log[
    (nc_log["weights_calculated"] > 0) &
    (nc_log["weights_calculated"] < 200)
]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
1350,2136,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_2136.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_2136.i3.zst,partially ok,processed only first 54 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,54,54,0.021442
2038,2761,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_2761.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_2761.i3.zst,partially ok,processed only first 120 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,120,120,0.071814
3348,3952,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_3952.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_3952.i3.zst,partially ok,processed only first 151 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,151,151,0.082551
3613,4193,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_4193.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_4193.i3.zst,partially ok,processed only first 51 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,51,51,0.061082
4075,4613,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_4613.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_4613.i3.zst,partially ok,processed only first 71 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,71,71,0.045190
6519,6835,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_6835.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_6835.i3.zst,partially ok,processed only first 111 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,111,111,0.067684
6785,7077,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_7077.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_7077.i3.zst,partially ok,processed only first 120 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,120,120,0.048136
6902,7183,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_7183.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_7183.i3.zst,partially ok,processed only first 30 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,30,30,0.112461
7763,7966,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_7966.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_7966.i3.zst,partially ok,processed only first 184 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,184,184,0.115382
8252,8410,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_8410.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_8410.i3.zst,partially ok,processed only first 50 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,50,50,0.099816
8626,8750,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_8750.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_8750.i3.zst,partially ok,processed only first 54 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,54,54,0.043758
9622,9656,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/genCard_9656.lic,/project/6008051/pone_simulation/MC000005-nu_NC-2_7-LeptonInjector_PROPOSAL_clsim_NC-v10/Generator/gen_9656.i3.zst,partially ok,processed only first 73 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,73,73,0.068917

In [12]:
muon_log[
    (muon_log["weights_calculated"] > 0) &
    (muon_log["weights_calculated"] < 200)
]

,batch_id,lic_file,i3_file,status,error,i3_file_opened_ok,bad_file_rule,max_daq_frames,weights_calculated,duration_s
19,19,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_019.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_019.i3,partially ok,processed only first 110 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,110,110,0.106493
30,30,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_030.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_030.i3,partially ok,processed only first 185 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,185,185,0.418628
38,38,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_038.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_038.i3,partially ok,processed only first 188 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,188,188,0.424352
83,84,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_084.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_084.i3,partially ok,processed only first 63 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,63,63,0.111764
88,89,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_089.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_089.i3,partially ok,processed only first 96 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,96,96,0.307848
...,...,...,...,...,...,...,...,...,...,...
9439,9656,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_9656.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_9656.i3,partially ok,processed only first 38 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,38,38,0.922871
9451,9667,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_9667.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_9667.i3,partially ok,processed only first 170 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,170,170,0.218571
9453,9669,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_9669.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_9669.i3,partially ok,processed only first 4 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,4,4,0.069226
9518,9728,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_9728.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_9728.i3,partially ok,processed only first 14 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,14,14,0.075298
9797,9981,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Generator/genCard_9981.lic,/project/6008051/pone_simulation/MC000002-nu_mu-2_7-LeptonInjector-PROPOSAL-clsim-v10/Photon/cls_9981.i3,partially ok,processed only first 21 DAQ frames per paths.BAD_I3_FILES,True,limit_daq,21,21,0.225534

In [13]:
muon_log[
    (muon_log["weights_calculated"] > 0) &
    (muon_log["weights_calculated"] < 200)
]["bad_file_rule"].value_counts()

bad_file_rule
limit_daq    223
Name: count, dtype: int64